version: '3'

networks:
  internal:

services:
  reverse-proxy:
    image: caddy:2
    ports:
      - 8001:8080
    networks:
      - internal
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

  ui:
    image: jaedle/vinotheque:ui-latest
    networks:
      - internal

  service:
    image: jaedle/vinotheque:service-latest
    networks:
      - internal
