version: '3'

networks:
  internal:

services:
  reverse-proxy:
    image: jaedle/vinotheque:reverse-proxy-latest
    ports:
      - 8001:8443
    networks:
      - internal
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./certificates:/certificates:ro
      - ./users.json:/users.json

  ui:
    image: jaedle/vinotheque:ui-latest
    networks:
      - internal

  service:
    image: jaedle/vinotheque:service-latest
    networks:
      - internal
