version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/e2e"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/service"
    schedule:
      interval: "daily"
