version: '3'

silent: true

tasks:
  world: 
    cmds:
      - task: check-preconditions
      - task: format-service
      - task: test-service
      - task: integration-test-service
      - task: e2e
      - task: cleanup-dependencies-service

  install:
    cmds:
      - task: install-tools
      - task: install-e2e-dependencies

  install-tools:
    cmds: ['$(cd $HOME && go get -u github.com/onsi/ginkgo/ginkgo)']

  install-e2e-dependencies:
    dir: e2e/
    cmds: [npm ci --no-progress]

  check-preconditions:
    cmds:
      - go version | grep 'go1.15' &> /dev/null
      - node --version | grep 'v14.' &> /dev/null
      - which ginkgo &> /dev/null

  format-service:
    dir: service/
    cmds: [go fmt ./...]

  test-service:
    dir: service/
    cmds: [ginkgo -r --skipPackage=integration]

  integration-test-service:
    dir: service/
    cmds: [ginkgo test/integration]

  cleanup-dependencies-service:
    dir: service/
    cmds: [go mod verify, go mod tidy]

  e2e:
    desc: run e2e test
    deps: [start-service]
    dir: e2e
    cmds: [npm run test]

  start-service:
    desc: locally start service
    deps: [stop-service]
    dir: service/
    env:
      PORT: 8080
    cmds:
      - screen -dmS service go run main.go
      - ./wait-healthy.sh
  stop-service:
    desc: locally stop service
    cmds: ['(! lsof -ti tcp:8080 &> /dev/null) || kill -9 $(lsof -ti tcp:8080) &> /dev/null']

  default:
    cmds: [task: world]
