version: '3'

silent: true

tasks:
  world: 
    cmds:
      - task: format-service
      - task: test-service

  format-service:
    dir: service/
    cmds:
      - go fmt ./...

  test-service:
    dir: service/
    cmds:
      - go test ./...

  default:
    cmds: [task: world]
