version: '3'

silent: true

tasks:
  world: 
    cmds:
      - task: check-preconditions
      - task: format-service
      - task: test-service
      - task: integration-test-service

  install-tools:
    cmds:
      - $(cd $HOME && go get github.com/onsi/ginkgo/ginkgo)

  check-preconditions:
    cmds:
      - go version | grep 'go1.14' &> /dev/null
      - which ginkgo &> /dev/null

  format-service:
    dir: service/
    cmds:
      - go fmt ./...

  test-service:
    dir: service/
    cmds:
      - ginkgo -r --skipPackage=integration

  integration-test-service:
    dir: service/
    cmds:
      - ginkgo test/integration

  default:
    cmds: [task: world]
