version: 1

update_configs:
  - package_manager: 'javascript'
    directory: '/e2e'
    update_schedule: 'live'
    version_requirement_updates: 'auto'
    automerged_updates:
      - match:
          update_type: 'all'

  - package_manager: 'javascript'
    directory: '/ui'
    update_schedule: 'live'
    version_requirement_updates: 'auto'
    automerged_updates:
      - match:
          update_type: 'all'

  - package_manager: 'go:modules'
    directory: '/service'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          update_type: 'all'
