on:
  push:
    branches:
      - "main"

name: Update release branch

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.0.0"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: task install
      - run: task world

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.0.0"
      - run: task build-docker-images

  release:
    name: Create Release
    runs-on: ubuntu-20.04
    needs: [test, build]
    steps:
      - uses: actions/checkout@v2
      - uses: Embraser01/update-git-branch-action@v1.0.0
        with:
          branch: release
          force: 1
          githubToken: ${{ secrets.GITHUB_TOKEN }} # Github Token