on: 
  push:
    branches-ignore:
      - 'main'
  pull_request:

name: test branches or pull requests

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.0.0"
      - uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: apt install libnss3-tools
      - run: task install
      - run: task register-local-domain
      - run: task world

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: Arduino/actions/setup-taskfile@master
        with:
          version: "3.0.0"
      - run: task build-docker-images
